// Generated by scripts/gen_linear_wasm.mjs, do not edit by hand.
// WASM SIMD sparse-input linear kernel (transposed weights, 4-lane outputs,
// sequential-k accumulation order, see the generator header for the parity
// contract). Source WAT kept at app/build/linsparse.wat.
export const LIN_WASM_B64 = "AGFzbQEAAAABCgFgBn9/f39/fwADAgEABQMBABAHDQIDbWVtAgADbGluAAAKlAEBkQEDBn8BewF/IAVBBGwhDSANIQpBACEGAkADQCAGIARODQEgACAGQQRsaigCACEHIAEgBkEEbGoqAgD9EyEMIAIgByANbGohCEEAIQkCQANAIAkgCk4NASADIAlqIQsgCyAL/QAEACAMIAggCWr9AAQA/eYB/eQB/QsEACAJQRBqIQkMAAsLIAZBAWohBgwACwsL";
