"""Build per-god card pool JSONs for the web app.

Reads:
  notes/card_bindata/*.json, raw card data (stats + effects)
  notes/localization_fr.json, FR names and descriptions (CARD_NAME_<id>, CARD_DESC_<id>)
  notes/enums.json, id ↔ name for God / SummonFamily / SummonProperty / etc.
  extracted/card_illustration_map.json, card → illustration mapping
  extracted/illustrations/, the actual PNG files

Writes (see pipeline/paths.py, override with $KROSMAGA_CARD_DATA):
  public/data/cards_<god>.json, one file per god
  public/illustrations/*.png, copies the illustrations referenced

Usage:
  KROSMAGA_WORKSPACE=/path/to/extraction python build_card_pool.py Iop Cra Ecaflip
"""
import sys, json, shutil
from pathlib import Path
sys.stdout.reconfigure(encoding="utf-8")

from paths import NOTES, EXTRACTED, CARD_DATA, ILLUSTRATIONS, require

BINDATA_DIR = require(NOTES / "card_bindata", "card bindata dump")
ENUMS = json.loads(require(NOTES / "enums.json", "enum table").read_text(encoding="utf-8"))
LOC = json.loads(require(NOTES / "localization_fr.json", "localization table").read_text(encoding="utf-8"))
ILLU_SRC = EXTRACTED / "illustrations"
OUT_DATA = CARD_DATA
OUT_ILLUS = ILLUSTRATIONS
OUT_DATA.mkdir(parents=True, exist_ok=True)
OUT_ILLUS.mkdir(parents=True, exist_ok=True)

def lookup(enum_name, value, fallback="None"):
    for v in ENUMS.get(enum_name, []):
        if v["id"] == value:
            return v["name"]
    return fallback

def short_type(t):
    """Strip the full Ankama type name down to its class name."""
    return (t or "").split(",")[0].split(".")[-1]

def unwrap_value(node):
    """Convert a ConstIntegerValue {$type:..., Value:N} to a plain number.
    Other Value subtypes (dynamic, random, etc.) are kept as objects with a
    simplified type field, the in-game shader cannot resolve them statically
    anyway, the description usually shows them as the base / displayed value."""
    if not isinstance(node, dict):
        return node
    t = short_type(node.get("$type"))
    if t == "ConstIntegerValue":
        return node.get("Value", 0)
    # For other value types (NumberOfSummonValue, TriggeringDiceValue, ...)
    # preserve the type but drop the $type prefix.
    out = {"type": t}
    for k, v in node.items():
        if k == "$type":
            continue
        out[k] = unwrap_value(v) if isinstance(v, dict) else v
    return out

def simplify_effect(eff):
    """Convert an Ankama Effect object into a flat record:
    {"type": "DamageData", "Damage": 5}
    {"type": "ShooterRangeData", "RangeMin": 1, "RangeMax": 2}
    {"type": "SetPropertyData", "PropertyType": "Charge"}
    {"type": "CreateCardCounterData", "InitialValue": 6, ...}
    """
    out = {"type": short_type(eff.get("$type"))}
    for k, v in eff.items():
        if k == "$type":
            continue
        # SetPropertyData.PropertyType is a SummonProperty enum id
        if out["type"] == "SetPropertyData" and k == "PropertyType":
            out[k] = lookup("SummonProperty", v, fallback=str(v))
            continue
        if isinstance(v, dict):
            out[k] = unwrap_value(v)
        elif isinstance(v, list):
            out[k] = [unwrap_value(x) if isinstance(x, dict) else x for x in v]
        else:
            out[k] = v
    return out

# Use the v2 illustration map which resolves illustrations via the
# original Ankama asset paths (m_illustration.m_assetPath) rather than
# fuzzy substring matching. Generated by scripts/rebuild_illustration_map.py.
ILLU_MAP_V2 = json.loads(
    require(NOTES / "illustration_map_v2.json", "illustration map").read_text(encoding="utf-8")
)
# Keys are stringified ints in the JSON
card_to_illu = {int(k): v for k, v in ILLU_MAP_V2["mapping"].items()}

# Evolution level for Infinite cards. Infinite cards come in "variant groups" of up to 3 cards: same
# template, different stats at each level. A card's evolution level (1/2/3) is its index in the
# variant's CardIds list. Cards not in any variant default to Lvl1.
#
# Each variant has its own frame PNG with 1/2/3 stars over the name band
# (card_front_summon_infinite1/2/3.png); that is how the game shows the evolution level.
VARIANTS_DIR = NOTES / "bindata" / "cardvariants"
card_to_evolution_level: dict[int, int] = {}
for vf in VARIANTS_DIR.glob("*.json"):
    try:
        vdata = json.loads(vf.read_text(encoding="utf-8"))
        for idx, cid in enumerate(vdata.get("CardIds", [])):
            card_to_evolution_level[cid] = idx + 1   # 1/2/3
    except Exception:
        pass

# Figurine map, small "preview" sprites that stand on the board cell
# when a summon is in play (distinct from the card illustration). Built
# by scripts/extract_summon_previews.py.
FIGURINE_MAP_PATH = NOTES / "figurine_map.json"
card_to_figurine: dict[int, str] = {}
if FIGURINE_MAP_PATH.exists():
    raw = json.loads(FIGURINE_MAP_PATH.read_text(encoding="utf-8"))
    card_to_figurine = {int(k): v for k, v in raw.items()}

# Card → Unity GAF model name (e.g. "do", "xel_ext3_h"). The runtime board
# renderer checks if /animations/<model>/manifest.json was extracted for that
# model; if yes, plays the animated GAF instead of the static figurine PNG.
# Source: extracted/card_to_model.json (scripts/build_card_to_model_map.py).
MODEL_MAP_PATH = EXTRACTED / "card_to_model.json"
card_to_model: dict[int, str] = {}
if MODEL_MAP_PATH.exists():
    raw = json.loads(MODEL_MAP_PATH.read_text(encoding="utf-8"))
    card_to_model = {int(k): v for k, v in raw.items()}

# CardType enum mapping (we want strings)
CARD_TYPE_NAMES = {0: "Summon", 1: "Spell", 2: "Aoe", 3: "Dofus", 4: "GameRules", 5: "EffectTemplate"}

# Synthetic effects parsed from the French description.
#
# Some mechanics (push, heal, etc.) only exist in the description text of the
# bindata. The original game resolves them on the server, so Effects[] only
# carries what the client needs (damage values, ranges...). To apply them in
# this engine we parse them at build time and create matching Effect records.
#
# Currently extracted:
#   - PushData {Distance: N}, from "repousse de N cases"
#
# More can be added here (heal, silence, stun, ...).
import re as _re
# Strip Ankama mini-markup so it does not confuse our regexes:
#   <b>…</b> / <i>…</i>   → drop the tags (keep content)
#   \_ / |_               → simple space
#   \n                    → real newline (we will split on it)
# Done in a tiny helper kept local to this module.
_TAG_RE = _re.compile(r"</?[bi]>")
def _norm_desc(desc: str) -> str:
    return (_TAG_RE.sub(" ", desc or "")
            .replace("\\_", " ").replace("|_", " ")
            .replace("\\n", "\n"))

# "repousse de N cases" / "repousse une invocation adverse de N cases"
# / "repoussez une invocation de N cases" / "repousse de N case"
# After _norm_desc the markup is gone, so we just need to find a `repouss`
# followed by `de N case(s)` somewhere later, possibly with arbitrary
# words between.
_PUSH_RE = _re.compile(
    r"repouss[a-z]*\b[^.]*?\bde\s+(\d+)\s*cases?",
    _re.IGNORECASE,
)

def synthesize_description_effects(desc: str) -> list[dict]:
    out: list[dict] = []
    clean = _norm_desc(desc or "")
    m = _PUSH_RE.search(clean)
    if m:
        out.append({"type": "PushData", "Distance": int(m.group(1))})
    return out

# ----------------- Trigger parser -----------------
#
# Trigger keywords look like `APPARITION :` / `MORT :` / `FIN DE TOUR :`
# (sometimes with no space before the colon). After normalising the
# description we split on these keywords; each section is the effect block
# of that trigger.
#
# Inside each section we look for known effect patterns:
#   - "S'inflige N dégâts"            → SelfDamageData
#   - "Gagne +N AT"                   → BoostAttackData
#   - "Gagne +N PV"                   → BoostLifeData
#   - "Se soigne de N PV"             → HealSelfData
#   - "Repouss... de N cases"         → PushData (usually aimed at another
#                                       creature; the engine skips it if it
#                                       cannot pick a target)
# When no pattern matches, the trigger is still registered with an empty
# effect list, so the UI can show the keyword.
#
# Returns a list of {trigger: TRIGGER_KEY, effects: [...]} dicts.

_TRIGGER_MAP = {
    "APPARITION":     "APPARITION",
    "MORT":           "MORT",
    "COUP DE GRACE":  "COUP_DE_GRACE",
    "COUP DE GRÂCE":  "COUP_DE_GRACE",
    "RALLIEMENT":     "RALLIEMENT",
    "FIN DE TOUR":    "FIN_DE_TOUR",
    "FIN DU TOUR":    "FIN_DE_TOUR",
    "DEBUT DE TOUR":  "DEBUT_DE_TOUR",
    "DÉBUT DE TOUR":  "DEBUT_DE_TOUR",
    "CONTRE COUP":    "CONTRE_COUP",
    "CONTRE-COUP":    "CONTRE_COUP",
}
# Regex that matches any of the keys, longest first to avoid prefix
# collisions ("COUP DE GRACE" before "COUP" if we ever add a bare
# "COUP" trigger). Followed by a ":" optionally preceded by whitespace.
_TRIGGER_RE = _re.compile(
    r"\b(" + "|".join(sorted((_re.escape(k) for k in _TRIGGER_MAP), key=len, reverse=True)) + r")\s*:",
    _re.IGNORECASE,
)

# Patterns that extract a self-targeted effect from a trigger's text body.
_SELF_DMG_RE   = _re.compile(r"s['’]inflige\s+(\d+)\s*(?:dégât|degat|dégats|degats|dgt)", _re.IGNORECASE)
_BOOST_AT_RE   = _re.compile(r"gagne\s+\+(\d+)\s*AT\b",  _re.IGNORECASE)
_BOOST_PV_RE   = _re.compile(r"gagne\s+\+(\d+)\s*PV\b",  _re.IGNORECASE)
_HEAL_SELF_RE  = _re.compile(r"se\s+soigne\s+(?:de\s+)?(\d+)\s*PV",  _re.IGNORECASE)

def _parse_trigger_body(body: str) -> list[dict]:
    """Extract synthetic effects from the text following a trigger keyword."""
    out: list[dict] = []
    if (m := _SELF_DMG_RE.search(body)):  out.append({"type": "SelfDamageData", "Damage": int(m.group(1))})
    if (m := _BOOST_AT_RE.search(body)):  out.append({"type": "BoostAttackData", "Boost": int(m.group(1))})
    if (m := _BOOST_PV_RE.search(body)):  out.append({"type": "BoostLifeData", "Boost": int(m.group(1))})
    if (m := _HEAL_SELF_RE.search(body)): out.append({"type": "HealSelfData", "Heal": int(m.group(1))})
    if (m := _PUSH_RE.search(body)):      out.append({"type": "PushData", "Distance": int(m.group(1))})
    return out

def parse_triggers(desc: str) -> list[dict]:
    """Walk the description, split on trigger keywords, parse each block."""
    clean = _norm_desc(desc)
    # Find every trigger occurrence + its position
    matches = list(_TRIGGER_RE.finditer(clean))
    if not matches:
        return []
    triggers: list[dict] = []
    for i, m in enumerate(matches):
        kw_norm = m.group(1).upper().replace("'", "")
        kw_norm = kw_norm.replace("É", "E").replace("È", "E")
        # Map back through original keys (some have accents in _TRIGGER_MAP)
        canonical = None
        for raw_kw, mapped in _TRIGGER_MAP.items():
            if raw_kw.replace("É", "E").replace("È", "E") == kw_norm:
                canonical = mapped
                break
        if canonical is None:
            continue
        # Body = text between this keyword and the next trigger (or end)
        end = matches[i + 1].start() if i + 1 < len(matches) else len(clean)
        body = clean[m.end():end]
        triggers.append({"trigger": canonical, "effects": _parse_trigger_body(body)})
    return triggers

def to_card_record(bindata: dict) -> dict | None:
    card_id = bindata.get("Id")
    if card_id is None:
        return None
    god = lookup("God", bindata.get("GodType", 0))
    rarity = lookup("CardRarity", bindata.get("Rarity", 0))
    card_type_id = bindata.get("CardType")
    card_type = CARD_TYPE_NAMES.get(card_type_id, "Unknown")
    families = [lookup("SummonFamily", f) for f in (bindata.get("Families") or [])]
    properties = [lookup("SummonProperty", p) for p in (bindata.get("Properties") or [])]
    spell_type = lookup("SpellType", bindata.get("SpellType", 0)) if card_type == "Spell" else None
    cast_target = lookup("CastTarget", bindata.get("CastTarget", 0), fallback="Unknown")

    # Localised name + description
    name = LOC.get(f"CARD_NAME_{card_id}") or f"#{card_id}"
    desc = LOC.get(f"CARD_DESC_{card_id}") or ""

    # Skip cards that are not shippable at all.
    if name.startswith("[notrad]") or "DEBUG" in name.upper():
        return None

    # Detect dev / debug / test cards that are shipped in the bundle but
    # are not intended for normal play. The Krosmaga build still contains
    # ~22 such cards (all neutral 0-PA spells) used internally by Ankama's
    # QA team. None of them have a CardData flag we can rely on, so we use
    # a heuristic on name + signature. Cards we keep in the JSON (so the
    # engine can opt-in to use them for testing) but flag with isDevCard.
    name_upper = name.upper()
    DEV_HARDCODED = {
        "FAKE !", "BLANQUETTE",
        "ENABLE PRISMS REPOP", "DISABLE PRISMS REPOP",
        "PRISME DE PA",
    }
    is_dev = (
        name.startswith("[DBG]")
        or name.startswith("#")                 # unlocalised → CARD_NAME_<id> missing
        or name_upper in DEV_HARDCODED
    )

    # Illustration: look it up and copy the file
    illu_path = None
    src_file = card_to_illu.get(card_id)
    if src_file:
        src = ILLU_SRC / src_file
        if src.exists():
            dst = OUT_ILLUS / f"{card_id}.png"
            # Always overwrite, the source mapping may have been corrected
            # (e.g. when rebuild_illustration_map.py fixes a wrong match).
            shutil.copy2(src, dst)
            illu_path = f"/illustrations/{card_id}.png"

    # Emission mask (warm-light overlay), copied separately by
    # scripts/copy_card_masks.py; we just check if the file exists.
    mask_path = None
    if (OUT_ILLUS / f"{card_id}_mask.png").exists():
        mask_path = f"/illustrations/{card_id}_mask.png"

    record = {
        "id": card_id,
        "name": name,
        "description": desc,
        "cardClass": bindata.get("$type", "").split(",")[0].split(".")[-1] or "Unknown",
        "cardType": card_type,
        "god": god,
        "rarity": rarity,
        "cost": bindata.get("CostAP", 0),
        "spellType": spell_type,
        "families": families,
        "properties": properties,
        "castTarget": cast_target,
        # True for the ~22 Ankama QA debug cards (kept in the pool so the
        # engine can opt-in to use them for testing, e.g. [DBG] Do 1 Damage
        # to validate a damage handler, but the UI should hide them by
        # default since they are not playable in a real deck).
        "isDevCard": is_dev,
        "effects": (
            [simplify_effect(e) for e in (bindata.get("Effects") or [])]
            + synthesize_description_effects(desc)
        ),
        "triggers": parse_triggers(desc),
        "illustration": illu_path,
        "illuMask": mask_path,
        "figurine": card_to_figurine.get(card_id),
        "model": card_to_model.get(card_id),
    }
    if card_type == "Summon":
        record["life"] = bindata.get("Life")
        record["attack"] = bindata.get("Attack")
        record["movement"] = bindata.get("MovementPoint")
    # Evolution level (only meaningful for Infinite cards). Defaults to 1
    # so consumers that always read this field do not crash on regular cards.
    if rarity == "Infinite":
        record["evolutionLevel"] = card_to_evolution_level.get(card_id, 1)
    return record

# Process per god
target_gods = sys.argv[1:] if len(sys.argv) > 1 else ["Iop", "Cra", "Ecaflip"]
print(f"Building pools for: {target_gods}\n")

# Load all bindata once
all_bindata = []
for f in sorted(BINDATA_DIR.glob("*.json"), key=lambda p: int(p.stem)):
    try:
        all_bindata.append(json.loads(f.read_text(encoding="utf-8")))
    except: pass
print(f"Loaded {len(all_bindata)} card bindata files\n")

for god in target_gods:
    pool = []
    illus_copied = 0
    for bd in all_bindata:
        rec = to_card_record(bd)
        if not rec:
            continue
        if rec["god"] != god:
            continue
        pool.append(rec)
        if rec["illustration"]:
            illus_copied += 1
    pool.sort(key=lambda c: (c["cost"], c["name"]))

    out = OUT_DATA / f"cards_{god.lower()}.json"
    out.write_text(json.dumps(pool, indent=2, ensure_ascii=False), encoding="utf-8")

    # Stats
    from collections import Counter
    rarities = Counter(c["rarity"] for c in pool)
    types = Counter(c["cardType"] for c in pool)
    print(f"=== {god} ===")
    print(f"  {len(pool)} cards → {out}")
    print(f"  illustrations: {illus_copied}/{len(pool)}")
    print(f"  by type: {dict(types)}")
    print(f"  by rarity: {dict(rarities)}")
    print()
